stages:
  - linting

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - python -m pip install --upgrade pip
    - pip install flake8 flake8-import-order flake8-quotes flake8-pep8-naming
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --import-order-style=google --max-line-length=88
  only:
    - main

black_check:
  stage: linting
  script:
    - pip install black
    - black --check .