stages:
  - linting

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - python -m pip install --upgrade pip
    - pip install flake8 flake8-import-order flake8-quotes pep8-naming
    - flake8 .
  only:
    - main

black_check:
  stage: linting
  script:
    - python -m pip install --upgrade pip
    - pip install black
    - black --check .