stages:
  - linting
  - black

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - python -m pip install --upgrade pip
    - pip install flake8 flake8-import-order flake8-quotes pep8-naming
    - flake8 . --inline-quotes="double"
  only:
    - main

black_check:
  stage: black
  script:
    - python -m pip install --upgrade pip
    - pip install black
    - black --config config.toml .
    - black --check . --line-length 80
