stages:
  - linting
  - black
  - testing

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install flake8 flake8-import-order flake8-quotes pep8-naming
    - flake8 . --inline-quotes="double"
  only:
    - main

black_check:
  stage: black
  script:
    - pip install black
    - black --config pyproject.toml .
    - black --check . --line-length 80


testing:
  stage: testing
  script:
    - python3 lyceum/manage.py test