stages:
  - linting
  - black
  - testing

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install flake8 flake8-import-order flake8-quotes pep8-naming
    - flake8 .
  only:
    - main

black_check:
  stage: black
  script:
    - pip install black
    - black --check --config pyproject.toml .


testing:
  stage: testing
  script:
    - pip install -r requirements/test.txt
    - cd lyceum
    - python manage.py test