# Generated by Django 4.2 on 2024-03-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="sender_name",
            field=models.TextField(null=True),
        ),
    ]
