# Generated by Django 4.2 on 2024-03-13 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0002_feedback_sender_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Получено"),
                    ("processing", "В обработке"),
                    ("answered", "Ответ дан"),
                ],
                default="received",
                max_length=20,
                verbose_name="Статус обработки",
            ),
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Время изменения статуса",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        max_length=20, verbose_name="Старый статус"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        max_length=20, verbose_name="Новый статус"
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="feedback.feedback",
                        verbose_name="Обратная связь",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "лог статуса",
                "verbose_name_plural": "логи статусов",
            },
        ),
    ]
