# Generated by Django 4.2 on 2024-03-14 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("feedback", "0005_alter_statuslog__from"),
        ("feedback", "0006_alter_statuslog_user"),
        ("feedback", "0007_alter_feedback_sender_name"),
        ("feedback", "0008_rename_sender_name_feedback_name"),
    ]

    dependencies = [
        (
            "feedback",
            "0002_feedback_sender_name_squashed_0004_rename_new_status_statuslog_to_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuslog",
            name="_from",
            field=models.CharField(
                db_column="from", max_length=20, verbose_name="Старый статус"
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="feedback",
            old_name="sender_name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
