# Generated by Django 4.2 on 2024-03-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0002_feedback_sender_name_squashed_0004_rename_new_status_statuslog_to_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuslog",
            name="_from",
            field=models.CharField(
                db_column="from", max_length=20, verbose_name="Старый статус"
            ),
        ),
    ]
