# Generated by Django 4.2 on 2024-03-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_alter_statuslog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="sender_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
