# Generated by Django 4.2 on 2024-03-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0005_alter_statuslog__from_squashed_0008_rename_sender_name_feedback_name",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="media")),
            ],
            options={
                "verbose_name": "изображение отзыва",
                "verbose_name_plural": "изображения отзыва",
                "db_table": "feedback_images",
            },
        ),
    ]
