# Generated by Django 4.2 on 2024-03-17 12:17

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    replaces = [
        ("feedback", "0009_feedbackimages"),
        (
            "feedback",
            "0010_remove_feedback_mail_remove_feedback_name_and_more",
        ),
        ("feedback", "0011_alter_feedbackimages_feedback_and_more"),
        ("feedback", "0012_alter_feedbackimages_image"),
    ]

    dependencies = [
        (
            "feedback",
            "0005_alter_statuslog__from_squashed_0008_rename_sender_name_feedback_name",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="mail",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="name",
        ),
        migrations.CreateModel(
            name="FeedbackAuther",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=50, verbose_name="имя")),
                (
                    "mail",
                    models.EmailField(
                        max_length=254, verbose_name="электронная почта"
                    ),
                ),
                (
                    "feedback",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auther",
                        to="feedback.feedback",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedbackImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=feedback.models.FeedbackImages.get_upload_path,
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="feedback.feedback",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение отзыва",
                "verbose_name_plural": "изображения отзыва",
                "db_table": "feedback_images",
            },
        ),
    ]
