# Generated by Django 4.2 on 2024-03-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0009_feedbackimages_squashed_0012_alter_feedbackimages_image",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackauther",
            name="name",
            field=models.TextField(
                blank=True, max_length=50, null=True, verbose_name="имя"
            ),
        ),
    ]
