# Generated by Django 4.2 on 2024-03-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0002_alter_profile_user_squashed_0004_remove_profile_coffe_count_profile_coffee_count",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="coffee_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="количество переходов по /coffee/"
            ),
        ),
    ]
