# Generated by Django 4.2 on 2024-03-03 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0002_alter_itemimages_image_and_more"),
        (
            "catalog",
            "0003_alter_item_images_alter_item_main_image_and_more",
        ),
        ("catalog", "0004_alter_item_images_alter_item_tags"),
    ]

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemimages",
            name="image",
            field=models.FileField(null=True, upload_to="uploads"),
        ),
        migrations.AlterField(
            model_name="itemmainimages",
            name="main_image",
            field=models.FileField(
                null=True,
                upload_to="uploads",
                verbose_name="Будет приведено к 1280px",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                help_text="Изображения товара",
                to="catalog.itemimages",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="main_image",
            field=models.OneToOneField(
                blank=True,
                help_text="Основное изображение",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.itemmainimages",
            ),
        ),
        migrations.AlterField(
            model_name="itemimages",
            name="image",
            field=models.FileField(null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="itemmainimages",
            name="main_image",
            field=models.FileField(
                null=True,
                upload_to="media",
                verbose_name="Главное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                help_text="Изображения товара",
                related_name="items",
                to="catalog.itemimages",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите метки для товара",
                related_name="items",
                to="catalog.tag",
            ),
        ),
    ]
