# Generated by Django 4.2 on 2024-02-20 16:14

from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0001_initial",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.category",
            ),
        ),
        migrations.RemoveField(
            model_name="item",
            name="tag",
        ),
        migrations.AddField(
            model_name="item",
            name="tag",
            field=models.ManyToManyField(to="catalog.tag"),
        ),
    ]
