# Generated by Django 4.2 on 2024-02-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemimages",
            name="image",
            field=models.FileField(null=True, upload_to="uploads"),
        ),
        migrations.AlterField(
            model_name="itemmainimages",
            name="main_image",
            field=models.FileField(
                null=True,
                upload_to="uploads",
                verbose_name="Будет приведено к 1280px",
            ),
        ),
    ]
