# Generated by Django 4.2 on 2024-02-20 16:43

import catalog.models
import django.core.validators
from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0002_alter_item_category_remove_item_tag_item_tag",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Статус публикации",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.TextField(
                help_text="Введите название",
                max_length=150,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.TextField(
                help_text="Введите уникальный набор букв и цифр",
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Значение должно содержать только цифры, буквы латиницы и символы - и _",
                        regex="^[a-zA-Z0-9_-]+$",
                    )
                ],
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.IntegerField(
                default=100,
                help_text="Введите вес категории",
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Вес",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию для товара",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Статус публикации",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.TextField(
                help_text="Введите название",
                max_length=150,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tag",
            field=models.ManyToManyField(
                help_text="Выберите метки для товара",
                to="catalog.tag",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Введите описание товара",
                validators=[catalog.models.text_validator],
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Статус публикации",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.TextField(
                help_text="Введите название",
                max_length=150,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.TextField(
                help_text="Введите уникальный набор букв и цифр",
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Значение должно содержать только цифры, буквы латиницы и символы - и _",
                        regex="^[a-zA-Z0-9_-]+$",
                    )
                ],
                verbose_name="Слаг",
            ),
        ),
    ]
