# Generated by Django 4.2 on 2024-02-21 16:44

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_name_alter_item_name_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Введите описание товара",
                validators=[
                    catalog.models.ValidateMustContain(
                        "роскошно", "превосходно"
                    )
                ],
                verbose_name="текст",
            ),
        ),
    ]
