# Generated by Django 4.2 on 2024-02-28 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_itemimages_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                help_text="Изображения товара",
                to="catalog.itemimages",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="main_image",
            field=models.OneToOneField(
                blank=True,
                help_text="Основное изображение",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.itemmainimages",
            ),
        ),
        migrations.AlterField(
            model_name="itemimages",
            name="image",
            field=models.FileField(null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="itemmainimages",
            name="main_image",
            field=models.FileField(
                null=True,
                upload_to="media",
                verbose_name="Главное изображение",
            ),
        ),
    ]
