# Generated by Django 4.2 on 2024-02-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category_current_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="current_name",
            field=models.CharField(
                editable=False, max_length=150, null=True, unique=True
            ),
        ),
    ]
