# Generated by Django 4.2 on 2024-02-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_item_images_alter_item_main_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                help_text="Изображения товара",
                related_name="items",
                to="catalog.itemimages",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите метки для товара",
                related_name="items",
                to="catalog.tag",
            ),
        ),
    ]
