# Generated by Django 4.2 on 2024-02-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_tag_current_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Введите уникальный набор букв и цифр",
                max_length=200,
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Введите уникальный набор букв и цифр",
                max_length=200,
                verbose_name="слаг",
            ),
        ),
    ]
