# Generated by Django 4.2 on 2024-02-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_category_slug_alter_tag_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="current_name",
            new_name="canonical_name",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="current_name",
            new_name="canonical_name",
        ),
    ]
