# Generated by Django 4.2 on 2024-02-26 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0005_rename_current_name_category_canonical_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.IntegerField(
                default=100,
                help_text="Введите вес категории",
                validators=[
                    django.core.validators.MaxValueValidator(32767),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="вес",
            ),
        ),
    ]
