# Generated by Django 4.2 on 2024-03-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_item_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemmainimages",
            old_name="main_image",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="item",
            name="images",
        ),
        migrations.RemoveField(
            model_name="item",
            name="main_image",
        ),
        migrations.AddField(
            model_name="itemimages",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.item",
            ),
        ),
        migrations.AddField(
            model_name="itemmainimages",
            name="item",
            field=models.OneToOneField(
                blank=True,
                help_text="Основное изображение",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.item",
            ),
        ),
        migrations.AlterField(
            model_name="itemimages",
            name="image",
            field=models.ImageField(null=True, upload_to="media"),
        ),
    ]
