# Generated by Django 4.2 on 2024-03-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_itemimages_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(default=False, verbose_name=""),
        ),
    ]
