# Generated by Django 4.2 on 2024-02-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_itemimages_itemmainimages"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="itemimages",
            table="item_images",
        ),
        migrations.AlterModelTable(
            name="itemmainimages",
            table="item_main_images",
        ),
    ]
