# Generated by Django 4.2 on 2024-02-27 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_itemimages_table_alter_itemmainimages_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="images",
            field=models.ManyToManyField(
                help_text="Изображения товара",
                null=True,
                to="catalog.itemimages",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="main_image",
            field=models.OneToOneField(
                help_text="Основное изображение",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.itemmainimages",
            ),
        ),
    ]
