# Generated by Django 4.2 on 2024-02-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_item_images_item_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="images",
            field=models.ManyToManyField(
                help_text="Изображения товара", to="catalog.itemimages"
            ),
        ),
    ]
