# Generated by Django 4.2 on 2024-03-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0005_alter_item_text_squashed_0009_alter_item_is_on_main",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False, verbose_name="Отобразить на главной"
            ),
        ),
    ]
