# Generated by Django 4.2 on 2024-03-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_item_is_on_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию для товара",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="itemmainimages",
            name="item",
            field=models.OneToOneField(
                blank=True,
                help_text="Основное изображение",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                to="catalog.item",
            ),
        ),
    ]
