# Generated by Django 4.2 on 2024-03-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0013_item_created_date_item_updated_date"),
        ("catalog", "0014_alter_item_created_date_alter_item_updated_date"),
    ]

    dependencies = [
        (
            "catalog",
            "0010_alter_item_is_on_main_squashed_0012_alter_itemmainimages_item",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="item",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
