# Generated by Django 4.2 on 2024-03-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0013_item_created_date_item_updated_date_squashed_0014_alter_item_created_date_alter_item_updated_date",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
